package entities;
// Generated 2020-02-14 00:05:38 by Hibernate Tools 4.3.1

/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

    private int id;
    private String title;
    private byte[] file;
    private String videoBase64String;

    public Video() {
    }

    public Video(int id) {
        this.id = id;
    }

    public Video(int id, String title, byte[] file) {
        this.id = id;
        this.title = title;
        this.file = file;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public byte[] getFile() {
        return this.file;
    }

    public void setFile(byte[] file) {
        this.file = file;
    }

    public String getVideoBase64String() {
        return videoBase64String;
    }

    public void setVideoBase64String(String videoBase64String) {
        this.videoBase64String = videoBase64String;
    }
}
