package entities;
// Generated 2020-02-13 19:43:25 by Hibernate Tools 4.3.1

import java.sql.Blob;

/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

    private int id;
    private String title;
    private Blob video;
    private String videoBase64String;

    public Video() {
    }

    public Video(int id, String title, Blob video) {
        this.id = id;
        this.title = title;
        this.video = video;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Blob getVideo() {
        return this.video;
    }

    public void setVideo(Blob video) {
        this.video = video;
    }

    public String getVideoBase64String() {
        return videoBase64String;
    }

    public void setVideoBase64String(String videoBase64String) {
        this.videoBase64String = videoBase64String;
    }
}
